FROM mup-tests-server
RUN apt-get update
RUN apt-get -y install wget lxc iptables curl && \
    wget -qO- https://get.docker.com/ | sh && usermod -aG docker $(whoami)
RUN echo 'DOCKER_OPTS="--storage-driver=vfs"' >> /etc/default/docker